name: release

on:
  release:
    types:
      - created

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Detect node version
        id: node-version
        run: echo "::set-output name=NODE_VERSION::$(cat .node-version)"
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.node-version.outputs.NODE_VERSION }}"
          registry-url: 'https://registry.npmjs.org'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
          key: release-yarn-${{ runner.os }}-${{ steps.node-version.outputs.NODE_VERSION }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            release-yarn-${{ runner.os }}-${{ steps.node-version.outputs.NODE_VERSION }}-${{ hashFiles('yarn.lock') }}
            release-yarn-${{ runner.os }}-${{ steps.node-version.outputs.NODE_VERSION }}-
            release-yarn-${{ runner.os }}-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Publish package
        run: npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
